version: '3'

services:
  test_db:
    container_name: test_db
    image: 'mysql:8.0.22'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contact_api_database_test
    tmpfs: /var/lib/mysql
  db:
    image: 'mysql:8.0.22'
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contact_api_database
    volumes:
      - contacts-db:/var/lib/mysql
  server:
    container_name: server
    depends_on:
      - db
    build: '.'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=contact_api_database
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - '5000:5000'
    command: 'bash -c "npm run wait-for-db && npm run start:watch"'

volumes:
  contacts-db:
