name: Integration tests
on:
  pull_request:
    branches: [main, dev]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: haltuf/mysql-action@master
        with:
          host port: 3308
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql database: 'contact_api_database_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'root' # Required if "mysql user" exists. The password for the "mysql user"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm i -g db-migrate db-migrate-mysql
      - run: DB_HOST_TEST=localhost DB_PORT_TEST=3308 DB_USER_TEST=root DB_PASS_TEST=root DB_NAME_TEST=contact_api_database_test db-migrate up -e test
      - run: npm test
        env:
          NODE_ENV: 'test'
          CI: true
          SERVER_PORT_TEST: 3001
          DB_DIALECT: mysql
          DB_HOST_TEST: localhost
          DB_USER_TEST: root
          DB_PASS_TEST: root
          DB_NAME_TEST: contact_api_database_test
          DB_PORT_TEST: 3308
          API_KEY: 'H56RT67FVgf233smn56FGgfPMnbCsz6'
